config/routes.rb
Components::Application.routes.draw do
  resources :fonts do 
    member { get :like }
  end

  resources :users
  root "static#home"
  get "static/home"
  get "static/about"
  get "static/contact"
  get "static/info"

  get ':controller(/:action(/:id))'
  get 'auth/failure', to: redirect('/')
  get 'auth/twitter/callback', to: 'sessions#create'
  get 'signout', to: 'sessions#destroy', as: 'signout'
  match 'users', to: 'users#index', via: 'get'

  match 'fonts/index', to: 'fonts#index', via: 'get'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all 
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
    can :manage, :all? { |e|  }
    else
     can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end

  def self.can? user, action, obj

    case obj.class
    when Font
       obj.user == user
    else
      raise ArgumentError.new "not implementing"
  end

end

app/models/font.rb
class Font < ActiveRecord::Base
	belongs_to :user
    has_reputation :likes, source: :user, aggregated_by: :sum
    attr_accessible :image, :fontnames, :html, :css, :description



  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :image, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '800x300>'
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :fonts

  def self.from_omniauth(auth)
  	where(auth.slice("provider", "uid", "name", "location", "image")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
  	create! do |user|
  	  user.provider = auth["provider"]
  	  user.uid = auth["uid"]
  	  user.name = auth["info"]["nickname"]
  	  user.location = auth["info"]["location"]
  	  user.image = auth["info"]["image"]
  	end
  end

end

app/controllers/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all 
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
    can :manage, :all
    else
     can :read, :all
     can :like, Font
     can :create, Font
     can :destroy, Font
     can :update, Font do |font|
     font.try(:user) == user 
    end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end

  # def self.can? user, action, obj

  #   case obj.class
  #   when Font
  #      obj.user == user
  #   else
  #     raise ArgumentError.new "not implementing"
  #   end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
  	flash[:error] = "Access Denied."
  	redirect_to root_url
  end

private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
    flash[:error] = "Record not found" and return unless @current_user
  end
  helper_method :current_user  
end

app/controllers/fonts_controller.rb
class FontsController < ApplicationController
  load_and_authorize_resource
  #before_action :set_font, only: [:show, :edit, :update, :destroy]

  def index
    @fonts = Font.find_with_reputation(:likes, :all, {:order => 'likes DESC'})
  end

  def show
  end

  def self.most_liked
  find_with_reputation(:likes, :all, {:order => 'likes DESC'})
  end

  def like
    value = params[:type] == "up" ? 1 : -1
    @font = Font.find(params[:id])
    @font.add_or_update_evaluation(:likes, value, current_user)
    redirect_to :back, notice: "Thanks for voting!"
  end  

  def new 
      @font  = current_user.fonts.build
  end


  def create
    @font = current_user.fonts.build(font_params)


    respond_to do |format|
      if @font.save
        format.html { redirect_to @font, notice: 'Font was successfully created.' }
        format.json { render action: 'show', status: :created, location: @font }
      else
        format.html { render action: 'new' }
        format.json { render json: @font.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @font = Font.find(params[:id])
    respond_to do |format|
      if @font.update(font_params)
        format.html { redirect_to @font, notice: 'Font was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @font.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @font = Font.find(params[:id])
    @font.destroy
    respond_to do |format|
      format.html { redirect_to fonts_url }
      format.json { head :no_content }
    end
  end

  private

  def image_params
  params.require(:image).permit(:title, :assets_attributes => [:filename, :id, :screenshot_id])
  end

    def font_params
      #params.require(:font).permit(:fontnames, :description, :html, :css, :name, :likes, :image)
       params.require(:font).permit! 
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
   user = User.from_omniauth(env["omniauth.auth"])
   session[:user_id] = user.id 
   redirect_to root_url, notice: "You are now signed in."
  end 

  def destroy
   session[:user_id] = nil
   redirect_to root_url, notice: "You are now signed out."
  end 
end		

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def info
  	render :layout => false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
  	@user = User.all
  end
  	
end

app/helpers/application_helper.rb
module ApplicationHelper
 
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
 
end

app/helpers/fonts_helper.rb
module FontsHelper
	def pluralize_without_count(string, count)
      count > 1 ? string.pluralize : string
    end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/fonts/_form.html.erb
<%= form_for (@font), :html => {:multipart => true} do |f| %>
  <% if @font.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@font.errors.count, "error") %> prohibited this font from being saved:</h2>

      <ul>
      <% @font.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <div class="field" >
    <%= f.label :fontnames %><br>
    <%= f.text_field :fontnames %>
  </div>
  <div class="input-large">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :html %><br>
    <%= f.text_field :html %>
  </div>
  <!-- <input type="text" class="form-control input-lg"> -->
   <div>
    <%= f.label :css %>
    <%= f.text_area :css %>
  </div>
<div class="field">
  <%= f.label :image %><br />
  <%= f.file_field :image %>
</div>


  <div class="actions">
    <%= f.submit %>
  </div>
 </div> 
<% end %>

app/views/fonts/edit.html.erb
<h1>Editing font</h1>

<%= render 'form' %>

<%= link_to 'Show', @font %> |
<%= link_to 'Back', fonts_path %>

app/views/fonts/index.html.erb
    <% @fonts.each do |font| %>
      <article>
        <h2><%= link_to(font.fontnames, font_path(font)) %>
        <p><%= font.description %></p>        
        <a href="<%= font.image.url %>" data-toggle="lightbox" data-title="<%= font.fontnames %>"><img src = <%= font.image.url %> class="img-responsive"</a>
        <br>
        <div>
        <p>Submitted by  <img src = <%= font.user.image.sub("_normal", "_mini") %> /> <%= link_to font.user.name, user_path(font.user) %></p>
        </div>
        <hr>
        </article>   
    <% end %>

app/views/fonts/new.html.erb
<h1>New font</h1>

<%= render 'form' %>

<%= link_to 'Back', fonts_path %>

app/views/fonts/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Components</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<h3>
  <%=link_to image_tag("redarrow.png"), :back %>
  <%= @font.fontnames %>
</h3>
<hr>
<!-- <p id><%= notice %></p> -->
<br>
  <p><%= @font.description %></p>
<br>
<a href="<%= @font.image.url %>" data-toggle="lightbox" data-title="<%= @font.fontnames %>"><img src = <%= @font.image.url %> class="img-responsive"</a>

<br>
<br>
<% if current_user.present? %>
<%= link_to "Vote Up", like_font_path(@font, type: "up"), method: "GET", :class => "btn btn-success" %>&nbsp;&nbsp;<%= link_to "Vote Down", like_font_path(@font, type: "down"), method: "GET", :class => "btn btn-danger" %>
<% end %>&nbsp;&nbsp;
<% if can? :update, @font %>
<%= link_to 'Edit', edit_font_path(@font), :class => "btn btn-warning btn-important pull-right" %>
<% end %>

<br>
<br>
<p>Submitted by:&nbsp;<img class="smallround" src="<%= @font.user.image %>">&nbsp;&nbsp;<%= link_to @font.user.name, user_path(@font.user) %></p>
<br>

  <h2>HTML<%= image_tag("arrow1.png") %></h2>
  <%= raw Pygments.highlight(@font.html) %>  
<br>
  <h2>CSS<%= image_tag("arrow1.png") %></h2>
  <%= raw Pygments.highlight(@font.css) %>

<%= link_to '<i class="icon-ok icon-white"></i> Do it'.html_safe, user_path(@user) %>

app/views/layouts/_navigation.html.erb
<div id="sidebar-wrapper">
  <ul class="sidebar-nav">
    <li class="sidebar-brand"><%= link_to "FONTRIOT", root_path %></li>
    <li><a href="#"><%= link_to "Font Index", fonts_path %></a></li>
    <li><%= link_to "Users", users_path %></li>
    <li><a href="#">Resources</a></li>
    <li><%= link_to "About", static_about_path %></li>          
    <li><a href="#">Contact</a></li>
    <br> 
    <% if current_user.present? %>
    <br>
    <li><i class="icon-twitter"></i><%= link_to "Sign Out", signout_path %>
  <li><img class="smallround" src="<%= current_user.image %>">    <i class="icon-user"></i></li>
  <li><%= link_to("View Profile", user_path(current_user)) %></li>
  <li><%= current_user.location %></li>
  <br>
  <li><%= link_to "Submit", new_font_path %></li> 
  <% else %>
  <br>
  <li><i class="icon-twitter"></i><%= link_to "Sign In", "/auth/twitter" %></li>
  <% end %>  
  </ul>  
</div>
<a id="menu-toggle" href="#" class="btn btn-default"><i class="icon-reorder"></i></a>
      
        <!-- All page content musr remain within the page-content inset div! -->
        <div class="page-content inset">      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app>
<head>
  <title>Components</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/css?family=Lato:300|Oswald:400" rel="stylesheet" type="text/css" />
  <!-- <link href="http://fonts.googleapis.com/css?family=Abel|Medula+One" rel="stylesheet" type="text/css" /> -->
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
</head>
<body>
<div id="wrapper">
      	
<%= render'layouts/navigation' %>	
<div class="page-content inset">
  <%= render partial: "shared/flash_messages", flash: flash %> 
<%= yield %>
</div>
</div>
      
</div>

</body>
    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>
    <!-- Put this into a custom JavaScript file to make things more organized -->
    <script>

    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("active");
    });
    </script>

    <script src="js/vendor/jquery-1.9.1.min.js"></script>
<script src="js/vendor/bootstrap.min.js"></script>

</html>

app/views/shared/_bigger_image.html.erb
_bigger_image.html.erb

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1><%=link_to image_tag("redarrow.png"), :back %>All Users</h1>
<hr>
  <% @user.each do |user| %>
    
      <img class="smallround" src="<%= user.image %>">
      <p><%= link_to user.name, user %>
       <p><%= user.location %></p>
      <hr>
      <% end %>

app/views/users/show.html.erb
<div class="col-md-12">
<h2><%=link_to image_tag("redarrow.png"), :back %><%= @user.name %> - <%= @user.location %></h2>
<hr>
<div class="row">
<div class= "col-xs-12 col-sm-6 col-md-6">
<img class="round" src="<%= @user.image.sub("_normal", "") %>">
<br>
<br>
<p>Submissions: <span class="badge"><%= @user.fonts.count %></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Street Cred: <span class="badge">110</span></p>
</div>

<div class= "col-xs-6 col-sm-6 col-md-6">
   <h3> Latest Submissions: </h3>
   <hr>
<% @user.fonts.each do |f| %>
<article>
<p><%= link_to(f.fontnames, font_path(f)) %></p>
<hr>
</article> 
<% end %>